---
apiVersion: v1
kind: Service
metadata:
  name: jmx
  namespace: tomcat
  labels:
    app.kubernetes.io/name: tomcat
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: 8088
      targetPort: 8088
  selector: 
    app.kubernetes.io/name: tomcat
