apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: tomcat
  name: jmx-config
  namespace: tomcat
data:
  config.yml: |
    startDelaySeconds: 0
    ssl: false
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
