---
# Source: tomcat/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tomcat
  namespace: default
  labels:
    app.kubernetes.io/name: tomcat
    helm.sh/chart: tomcat-10.3.11
    app.kubernetes.io/instance: tomcat
    app.kubernetes.io/managed-by: Helm
  annotations:
    prometheus.io/scrape: "true"
type: Opaque
data:
  tomcat-password: "cGFzczEyMzQ="
