---
# Source: filebeat/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elk-filebeat-cluster-role-binding
  labels:
    app: "elk-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "elk"
roleRef:
  kind: ClusterRole
  name: elk-filebeat-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: elk-filebeat
  namespace: default
