---
# Source: filebeat/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elk-filebeat
  annotations:
  labels:
    app: "elk-filebeat"
    chart: "filebeat-7.17.3"
    heritage: "Helm"
    release: "elk"
