apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elk
resources:
- elasticsearch/templates/service.yaml
- elasticsearch/templates/statefulset.yaml
- filebeat/templates/clusterrole.yaml
- filebeat/templates/clusterrolebinding.yaml
- filebeat/templates/configmap.yaml
- filebeat/templates/daemonset.yaml
- filebeat/templates/deployment.yaml
- filebeat/templates/role.yaml
- filebeat/templates/rolebinding.yaml
- filebeat/templates/serviceaccount.yaml
- kibana/templates/deployment.yaml
- kibana/templates/service.yaml
